services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: roadmap
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: